language: node_js

node_js:
  - stable

install:
  - npm install

before_script:
  - npm run build-ts

script:
  - npm run test

# Send coverage data to Coveralls
after_script: "cat coverage/lcov.info | node_modules/coveralls/bin/coveralls.js"

after_success:
  - npm run typedoc